namespace CherryTranslate.Core;

/// <summary>
/// A safe, user-facing translation failure.  Messages are intentionally
/// generated by the client and never contain an API response body or secret.
/// </summary>
public sealed class TranslationException : Exception
{
    public TranslationException(string message)
        : base(message)
    {
    }
}
